packages:
  - name: qr
    actions:
      - name: qr 
        runtime: nodejs:default
environment:
  #LOG_DESTINATIONS: ${LOG_DESTINATIONS}
  LOG_DESTINATIONS: '[{"logtail":{"token":"uAHyJLbRPe4JnL9HVethjnTa"}}]'
